### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by TryHard3r** [DXkite/freebuf-stream-shell#1]
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in HelloStream.php on line 64

**Comment by dxkite** [comment]
emmm, 你用我这个代码，freebuf上面的代码没贴全

**Comment by TryHard3r** [comment]
你好，GitHub上代码运行也是这个错误，一位朋友给了我他改过后的代码没问题，谢谢啦

**Comment by dxkite** [comment]
![image](https://user-images.githubusercontent.com/7450707/43175524-1b965528-8ff2-11e8-9915-28148123b10d.png)

我这里没有你说的那个文件，就很尴尬啊?
